source 'https://rubygems.org'
gem 'roxml'
gem 'nokogiri'
gem 'cleanroom'
gem 'rspec'
gem 'nokogiri-diff'
gem 'simplecov'
gem 'simplecov-html'
gem 'rubytree'
gem 'hashdiff'
gem 'multiset'
gem 'sexp_processor'
gem 'ruby2ruby'
gem 'differ'
gem 'ruby-prof'
gem 'roundtrip_xml', path: '../'
gem 'rake'
